import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { BuildOptions, VaultIndex } from "./types.js";
import { readVault } from "./parse/vault.js";
import { collectRooms } from "./parse/rooms.js";
import { PLACEHOLDER_IMAGE, generateRooms } from "./graph/autoroom.js";
import { buildTags } from "./graph/containment.js";
import { noteOutputPath, renderNotePage, renderTagIndex, renderTagPage, tagHref, } from "./render/pages.js";
import { escapeHtml, shell } from "./render/html.js";
const HERE = path.dirname(fileURLToPath(import.meta.url));
export async function indexVault(options: BuildOptions): Promise<VaultIndex> {
    const notes = await readVault(options);
    const tags = buildTags(notes);
    const index: VaultIndex = {
        notes: new Map(notes.map((n) => [n.path, n])),
        tags,
        rooms: collectRooms(notes),
        assets: new Set<string>(),
        root: options.vault,
    };
    index.rooms = generateRooms(index);
    for (const room of index.rooms.values()) {
        if (room.image && room.image !== PLACEHOLDER_IMAGE) {
            index.assets.add(room.image.replace(/^\.?\//, ""));
        }
        for (const hotspot of room.hotspots) {
            if (hotspot.asset)
                index.assets.add(hotspot.asset.replace(/^\.?\//, ""));
        }
    }
    return index;
}
async function writePage(outDir: string, relPath: string, html: string): Promise<void> {
    const target = path.join(outDir, relPath);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, html, "utf8");
}
async function copyAssets(outDir: string): Promise<void> {
    const src = path.join(HERE, "assets");
    const dest = path.join(outDir, "assets");
    await fs.mkdir(dest, { recursive: true });
    for (const file of await fs.readdir(src)) {
        await fs.copyFile(path.join(src, file), path.join(dest, file));
    }
}
async function copyVaultAssets(index: VaultIndex, outDir: string): Promise<string[]> {
    const missing: string[] = [];
    for (const rel of index.assets) {
        const from = path.join(index.root, rel);
        const to = path.join(outDir, "vault", ...rel.split("/"));
        try {
            await fs.mkdir(path.dirname(to), { recursive: true });
            await fs.copyFile(from, to);
        }
        catch {
            missing.push(rel);
        }
    }
    return missing.sort();
}
function renderHome(index: VaultIndex, base: string, siteTitle: string): string {
    const tags = [...index.tags.values()].sort((a, b) => b.notes.length - a.notes.length || a.name.localeCompare(b.name));
    const roots = tags.filter((t) => t.parents.length === 0).slice(0, 12);
    const cards = roots
        .map((t) => {
        const sub = t.children.length
            ? `<span class="tag-sub">${t.children.length} sub-concept${t.children.length === 1 ? "" : "s"}</span>`
            : "";
        return `<li class="tag-card"><a href="${tagHref(base, t)}">
      <span class="tag-name">#${escapeHtml(t.name)}</span>
      <span class="tag-count">${t.notes.length} note${t.notes.length === 1 ? "" : "s"}</span>
      ${sub}
    </a></li>`;
    })
        .join("");
    const body = `<article class="index-page">
  <header class="page-head">
    <h1>${escapeHtml(siteTitle)}</h1>
    <p class="lede">${index.notes.size} note${index.notes.size === 1 ? "" : "s"}, ${index.tags.size} concept${index.tags.size === 1 ? "" : "s"}.</p>
  </header>
  <section class="panel">
    <h2>Start here</h2>
    <p class="panel-note">The broadest concepts — those no other concept contains.</p>
    <ul class="tag-grid">${cards}</ul>
  </section>
  <section class="panel">
    <h2>Everything</h2>
    <p class="panel-note"><a href="${base}/tags/">Browse all ${index.tags.size} concept${index.tags.size === 1 ? "" : "s"} →</a></p>
  </section>
</article>`;
    return shell({ title: "Home", siteTitle, base, body });
}
export interface BuildResult {
    notes: number;
    tags: number;
    pages: number;
    rooms: number;
    authoredRooms: number;
    out: string;
    unresolved: string[];
    missingAssets: string[];
    sizeWarnings: string[];
}
async function writeBreakpoint(outDir: string, breakpoint: number): Promise<void> {
    const css = `/* Generated by tektite — the width below which rooms fall back to lists. */
@media (max-width: ${breakpoint - 1}px) {
  .room-stage {
    display: none;
  }
  .panels-fallback {
    display: grid;
  }
}
`;
    await fs.writeFile(path.join(outDir, "assets", "breakpoint.css"), css, "utf8");
}
export async function build(options: BuildOptions): Promise<BuildResult> {
    const index = await indexVault(options);
    const { out, base, title } = options;
    const authored = [...index.rooms.values()].filter((r) => r.source).length;
    await fs.mkdir(out, { recursive: true });
    let pages = 0;
    const unresolved: string[] = [];
    await writePage(out, "index.html", renderHome(index, base, title));
    pages++;
    await writePage(out, path.join("tags", "index.html"), renderTagIndex(index, base, title));
    pages++;
    for (const tag of index.tags.values()) {
        const result = renderTagPage(tag, index, base, title);
        await writePage(out, path.join("tags", tag.slug, "index.html"), result.html);
        for (const target of result.unresolved)
            unresolved.push(`#${tag.name} -> ${target}`);
        pages++;
    }
    const sizeWarnings: string[] = [];
    for (const room of index.rooms.values()) {
        if (room.absoluteWithoutSize) {
            sizeWarnings.push(`#${room.tag}: absolute size/position needs width and height on the room note`);
        }
    }
    for (const note of index.notes.values()) {
        await writePage(out, path.join(...noteOutputPath(note.slug), "index.html"), renderNotePage(note, index, base, title));
        pages++;
    }
    await copyAssets(out);
    await writeBreakpoint(out, options.breakpoint);
    const missingAssets = await copyVaultAssets(index, out);
    return {
        notes: index.notes.size,
        tags: index.tags.size,
        rooms: index.rooms.size,
        authoredRooms: authored,
        pages,
        out,
        unresolved,
        missingAssets,
        sizeWarnings,
    };
}
